name: Python Linter & Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pylint
          pipenv install --dev

      - name: Lint with pylint
        run: |
          pipenv run pylint . || true

      - name: Test with pytest
        run: |
          pipenv run pytest || true

      - name: Comment PR with Test Summary
        if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "✅ CI completed: Linting and testing executed."