name: Python Linter & Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pylint
          pipenv install --dev

      - name: Lint with pylint
        run: |
          pipenv run pylint . || true

      - name: Test with pytest
        run: |
          pipenv run pytest || true




      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: Auto create RP if not on main
        if : github.event_name == 'push' && "${GITHUB_REF##*/}" != 'main'
        uses: actions/github-script@v7
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          script: |
            const title = process.env.TITLE;
            console.log(title)
            console.log("toto")


      - name: Comment PR with Test Summary
        if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "✅ CI completed: Linting and testing executed."
          
