name: Python Linter & Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pylint
          pipenv install --dev

      - name: Lint with pylint
        run: |
          pipenv run pylint . || true

      - name: Test with pytest
        run: |
          pipenv run pytest || true



      - name: Get current Branch
        uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          script: return "${GITHUB_REF##*/}"
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} (${{steps.my-script.outputs.result}})
      
      - name: Auto create RP if not on main
        if : github.event_name == 'push' && ${{steps.my-script.outputs.result}} != 'main'
        uses: actions/github-script@v7
        with:
          script: |
            console.log("toto")
            apk add jq curl
            curl --request GET --url "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_BEFORE_SHA/merge_requests" --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"


      - name: Comment PR with Test Summary
        if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "✅ CI completed: Linting and testing executed."
          
